apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-deployment
  labels:
    app: api-deployment
spec:
  serviceName: api-deployment
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
      sidecar: grokexporter-deployment
  template:
    metadata:
      labels:
        app: api-deployment
        sidecar: grokexporter-deployment
    spec:
      containers:
        - name: api-deployment
          image: apiimage
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: api-volume
              mountPath: /var/log/
        - name: grok
          image: dalongrong/grok-exporter
          imagePullPolicy: Always
          ports:
            - containerPort: 9144
          volumeMounts:
            - name: grokexporter-configmap
              mountPath: /etc/grok_exporter
            - name: api-volume
              mountPath: /var/log/
      volumes:
        - name: grokexporter-configmap
          configMap:
            name: grokexporter-configmap
        - name: api-volume
          persistentVolumeClaim:
            claimName: api-pvc
        
---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
  selector:
    app: api-deployment


