apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - name: redis-deployment
        image: redis
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
  type: LoadBalancer
  selector:
    app: redis-deployment


#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: cachedata-persistentvolume
#  labels:
#    type: local
#spec:
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/data/cachedata-persistentvolume"

#---

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: cachedata-persistentvolumeclaim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: ""
#  volumeName: cachedata-persistentvolume
#  resources:
#    requests:
#      storage: 2Gi
